"""post.user_id pos change

Revision ID: 1115ca39228c
Revises: 8313c4c21ed4
Create Date: 2024-04-18 20:02:59.401098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1115ca39228c'
down_revision = '8313c4c21ed4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
