"""post.type enum

Revision ID: f3b4764790b8
Revises: 1336ec2c2de5
Create Date: 2025-03-08 06:25:54.398772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3b4764790b8'
down_revision = '1336ec2c2de5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
